Changed option names according to the option style guide
jasp-stats/jaspSem pull request #100
Opened 2022-08-18 16:38 UTC by LSLindeloo

fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2044
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2045
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2046
fixes https://github.com/jasp-stats/INTERNAL-jasp/issues/2047

2022-08-18 16:56 UTC, LSLindeloo commented
Somehow, the unit tests fail on macOS because the tables get filled with zeros, do you know how to solve this?

2022-08-24 12:19 UTC, Kucharssim requested changes
Looks good so far, suggestions below

also, please rename `modelName` -> `name` (in the `models` `TabView` in SEM)

2022-08-24 12:19 UTC, Kucharssim commented on inst/qml/SEM.qml
> +			CheckBox { name: "manifestInterceptZeroFix";	label: qsTr("Fix manifest intercepts to zero")					}
the same for `latentIntercept`

2022-08-24 12:19 UTC, Kucharssim commented on inst/qml/MediationAnalysis.qml
> +            name:  "dependents"
```suggestion
            name:  "outcomes"
```

2022-08-24 12:19 UTC, Kucharssim commented on inst/qml/MediationAnalysis.qml
> +                name: "samplingMethod"
```suggestion
                name: "errorCalculationMethod"
```

2022-08-24 12:19 UTC, Kucharssim commented on inst/Upgrades.qml
> +		functionName: "LatentGrowthCurve";	fromVersion: "0.15";	toVersion: "0.16";
can you change the version in `DESCRIPTION` and `inst/Description.qml` to `0.16.4`? Then use the `fromVersion: 0.16.3` and `toVersion: 0.16.4`. Also, perhaps put those on separate lines for better readability :)

2022-08-24 12:19 UTC, Kucharssim commented on inst/Upgrades.qml
> +					case "EQS":	return "eqs";
if there are RadioButtons that were not changed like here (i.e., `lavaan`), you'll need to catch them with a default statement
```suggestion
					case "EQS":	return "eqs";
					default:	return options["emulation"];
```

2022-10-12 12:20 UTC, Kucharssim approved these changes

2022-10-12 12:20 UTC, merged