Added some clear error messages and fixed stdResidsCovTab issue
jasp-stats/jaspSem pull request #107
Opened 2022-09-22 14:36 UTC by LSLindeloo

fixes https://github.com/jasp-stats/jasp-test-release/issues/2008, https://github.com/jasp-stats/jasp-test-release/issues/2009, https://github.com/jasp-stats/jasp-test-release/issues/2010, https://github.com/jasp-stats/jasp-test-release/issues/2011

2022-09-22 15:29 UTC, LSLindeloo commented
The reason why the standardized residual covariance matrix cannot be computed for se method 'bootstrap', is because `lavaan::lav_model_h1_acov()` doesn't return the Asymptotic Covariance Matrix if the se method is set to 'bootstrap':

`# which type of se?
if(lavoptions$se %in% c("standard", "none")) {
    ACOV[[g]] <- 1/Ng * I1.g.inv
} else if(lavoptions$se %in% c("robust.huber.white", "robust.sem")) {
    ACOV[[g]] <- 1/Ng * (I1.g.inv %*% J1[[g]] %*% I1.g.inv)
}
}

ACOV
}`

Do you have any idea why this could be the case? 
I tried to find out how to compute the ACOV in case of se method = 'bootstrap', but untill now I haven't found a clear answer.

2022-09-23 08:27 UTC, Kucharssim requested changes
good work, all issues are fixed! Just little nitpicks

2022-09-23 08:27 UTC, Kucharssim commented on R/sem.R
> +      missingFootnote <- gettextf("A total of %g cases were removed due to missing values. You can avoid this by choosing 'FIML' under 'Missing Data Handling' in the Estimation options.",
this is probably fine, but `%s` would be probably sufficient, or perhaps `%i` if you want to insist that it's an integer
```suggestion
      missingFootnote <- gettextf("A total of %g cases were removed due to missing values. You can avoid this by choosing 'FIML' under 'Missing Data Handling' in the Estimation options.",
```

2022-09-23 08:27 UTC, Kucharssim commented on R/sem.R
> +      fitic$addColumnInfo(name = "value", title = gettext("Value"), type = "number", format = "sf:4;dp:3")
I am not sure why this formatting was added in the first place, but it seems redundant (you can remove it for the other columns as well).
```suggestion
      fitic$addColumnInfo(name = "value", title = gettext("Value"), type = "number")
```

2022-09-23 08:27 UTC, Kucharssim commented on R/sem.R
> +        srtab$setError(gettext("The standardized residual covariance table is currently unavailable when the error calculation method is 'Bootstrap'"))
alternatively you can just ignore this option and disable the standardized residuals option in QML when `bootstrap` is selected. But this is a fine solution as it is.

2022-09-26 10:51 UTC, boutinb commented
@LSLindeloo Would it be possible to correct today this fix according to the remarks of Simon? It would be nice to be able to have a release this week.

2022-09-26 12:12 UTC, Kucharssim approved these changes

2022-09-26 12:13 UTC, merged

2022-10-11 08:27 UTC, LSLindeloo commented
Yes, of course!  Will do it right away!

Op ma 26 sep. 2022 om 12:51 schreef bruno boutin ***@***.***>:

> @LSLindeloo <https://github.com/LSLindeloo> Would it be possible to
> correct today this fix according to the remarks of Simon? It would be nice
> to be able to have a release this week.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jasp-stats/jaspSem/pull/107#issuecomment-1257848221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWNHG37HZEFE2LFBBD4IRKTWAF54JANCNFSM6AAAAAAQTD4TXQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>