added t size rmsea and cfi
jasp-stats/jaspSem pull request #112
Opened 2022-10-05 14:24 UTC by LSLindeloo

fixes https://github.com/jasp-stats/jasp-issues/issues/1837

I am not sure whether to add the t size equivalents of the frequently used cutoff values for the rmsea and cfi, since there is no consensus on these values and the use is controversial

2022-10-07 11:07 UTC, LSLindeloo commented
fixes https://github.com/jasp-stats/jasp-issues/issues/1837

2022-10-12 14:07 UTC, Kucharssim commented on R/sem.R
> +    fitot[["value"]] <- fmli[[1]][c("rmsea", "rmsea.ci.lower", "rmsea.ci.upper", "rmsea.pvalue", "rmsea.t",
can you add citations of the original T-size articles to the tables that report these measures?

2022-11-09 11:24 UTC, Kucharssim commented
any development @LSLindeloo ? :)

2022-11-15 07:56 UTC, Kucharssim requested changes
Just one little thing

2022-11-15 07:56 UTC, Kucharssim commented on R/sem.R
> +    cfi_t_footnote <- paste0(gettextf("The T-size equivalents of the conventional CFI cut-off values (poor < 0.90 < fair < 0.95 < close) are <b>poor < %s < fair < %s < close</b> for model: ",
this footnote should be all formatted with a `gettextf` + use positional arguments (see https://github.com/jasp-stats/INTERNAL-jasp/issues/2125)

2022-11-16 09:49 UTC, Kucharssim approved these changes

2022-11-16 09:50 UTC, merged