added n(Parameters) to fit table
jasp-stats/jaspSem pull request #139
Opened 2023-01-21 12:59 UTC by LSLindeloo

fixes https://github.com/jasp-stats/jasp-issues/issues/716

2023-03-01 11:08 UTC, Kucharssim requested changes
The feature looks ok, but there is some confusion with calling the internal functions. Let's fix that first

2023-03-01 11:08 UTC, Kucharssim commented on tests/testthat/test-mediationanalysis.R
> +  results <- jaspTools::runAnalysis("MediationAnalysisInternal","test.csv", options)
hm this should stay the same, i.e., callling the wrapper function, not the internal one. Could you remove these changes and make sure to rebase?

2024-08-07 13:01 UTC, juliuspfadt approved these changes

2024-08-07 13:04 UTC, juliuspfadt commented
@Kucharssim I need your approval 🙂

2024-08-08 11:06 UTC, merged