added fit by group table
jasp-stats/jaspSem pull request #145
Opened 2023-02-17 11:52 UTC by LSLindeloo

https://github.com/jasp-stats/jasp-issues/issues/711 (fixed for SEM)

2023-03-01 11:01 UTC, Kucharssim requested changes
looks great, just a couple of comments

2023-03-01 11:01 UTC, Kucharssim commented on R/sem.R
> +      grouptab$addColumnInfo(name = "ddf",      title = gettext("\u0394df"),           type = "integer",
here we only want to translate the "df"
```suggestion
      grouptab$addColumnInfo(name = "ddf",      title = gettextf("%1$sdf", "\u0394"),           type = "integer",
```

2024-02-21 15:32 UTC, juliuspfadt commented
![Screenshot 2024-02-21 at 16 32 27](https://github.com/jasp-stats/jaspSem/assets/38500953/4011bbb7-34d3-422e-af42-938da21d11d3)

2024-02-21 16:32 UTC, juliuspfadt commented
It also seems very annoying that we have to fit the model again for each group, if only lavaan would give us the AIC and BIC

2024-02-21 16:58 UTC, juliuspfadt commented on R/sem.R
> +        fit_group <- try(do.call(lavaan::lavaan, lav_args))
@Kucharssim, this code does not work when there are equality constraints, which is not surprising. Lorenzo fits the model for the subgroup only, but with invariance testing equality constraints are between the two groups, e.g., the loadings of group1 are equal to the loadings of group2. It seems to me that the equality constraints do not matter for the fit of each group, so we should estimate the model with free parameters unless some the constraints are not between groups but within a group. I wonder how we would find distinguish here though....

2024-02-23 13:39 UTC, juliuspfadt commented
Okay, this should be ready as well. this is what I eventually settled on: 
<img width="715" alt="Screenshot 2024-02-23 at 14 37 53" src="https://github.com/jasp-stats/jaspSem/assets/38500953/883deccd-a08c-4e9f-9895-2e85cdeb75cc">
I actually think it makes little sense to get the fit per group cause giving a grouping variable is not the same as fitting one model per group. The fit function is minimized for the complete model with a group variable. so the fit of the groups is the same as the fit of the complete model.

2024-04-30 17:37 UTC, juliuspfadt commented
now like this: 
<img width="1582" alt="Screenshot 2024-04-30 at 19 36 39" src="https://github.com/jasp-stats/jaspSem/assets/38500953/aa62b67b-0e1d-4f19-9d82-3f1287ae6304">

2024-05-17 10:15 UTC, juliuspfadt commented
I suppose I should've checked, weird that I didn't notice the test failing. It's caused by imposing meanstructure but then not fixing any intercepts to 0. I wonder if in qml there is an option for something like a triple of checkboxes, they can be all checked but not unchecked simultaneously. Suppose .quitAnalysis will have to do for now.

2024-05-21 12:03 UTC, merged