PLSSEM v1
jasp-stats/jaspSem pull request #94
Opened 2022-07-12 11:48 UTC by LSLindeloo

This analysis still needs some inprovements, especially creating a specialized text area for cSEM

2022-08-30 15:58 UTC, JorisGoosen commented
the new csem model component has been merged

2022-09-06 21:35 UTC, LSLindeloo commented
I think the PLS Sem analysis is quite solid now. I decided to remove the nonlinear model options, since many functions in the csem package are not suitable for non linear models. I could still add a test for multiple group differences, predictions of indicator scores of endogenous constructs and prediction metrics, and maybe some other small functions. What do you think of it so far? Do you have any suggestions?

2022-12-02 11:00 UTC, Kucharssim requested changes
This looks really impressive! I did not find any errors so far, looks quite robust.

I left a couple of minor code suggestions

Please rebase before changing the code and make sure the tests pass

2022-12-20 07:54 UTC, Kucharssim requested changes
a couple of left over suggestions

2022-12-20 07:54 UTC, Kucharssim commented on R/sem.R
> +    latents <- unique(parsed[parsed$op == "=~"]$lhs)
`parsed` is a data.frame, right? Doesn't this change break SEM then? 
```suggestion
    latents <- unique(parsed[parsed$op == "=~",]$lhs)
```

2022-12-20 07:54 UTC, Kucharssim commented on inst/qml/PLSSEM.qml
> +		title: "Prediction"
```suggestion
		title: qsTr("Prediction")
```

2022-12-20 07:54 UTC, Kucharssim commented on R/plssem.R
> +  options[["models"]] <- lapply(options[["models"]], fixModel)
Still think you don't need this ;)

2022-12-20 07:54 UTC, Kucharssim commented on R/plssem.R
> +      err <- "There are not enough observations for each k-fold, try setting 'cross-validation k-folds' to a lower number"
```suggestion
      err <- gettext("There are not enough observations for each k-fold, try setting 'cross-validation k-folds' to a lower number")
```

2022-12-20 07:54 UTC, Kucharssim commented on R/plssem.R
> +      err <- "Are all indicator variables set to 'scale'?"
```suggestion
      err <- gettext("Are all indicator variables set to 'scale'?")
```

2022-12-20 07:54 UTC, Kucharssim commented on R/plssem.R
> +.plsSemMardiasCoefficient <- function(modelContainer, dataset, options, ready) {
This still needs to be removed - just use `.semMardiasCoefficient()`

2022-12-20 07:54 UTC, Kucharssim commented on R/plssem.R
> +      oictab <- createJaspTable("Observed indicator correlation matrix")
```suggestion
      oictab <- createJaspTable(gettext("Observed indicator correlation matrix"))
```
the `gettext`s are missing from other tables in this function as well

2022-12-20 07:54 UTC, Kucharssim commented on R/plssem.R
> +      oictab <- createJaspTable("Observed indicator correlation matrix")
also optionally, you could use `%setOrRetrieve%` (see `` ?jaspBase::`%setOrRetrieve%` ``) for generating the tables to make the code a bit more succinct

2022-12-20 11:32 UTC, Kucharssim commented
@LSLindeloo have you committed anything since my review? I see you requested another review but there are no changes...

2022-12-20 11:41 UTC, LSLindeloo commented
@Kucharssim Sorry, I was a bit too enthusiastic :P! I will commit trhe changes in a minute!

2022-12-20 11:43 UTC, LSLindeloo commented
@Kucharssim The only thing is that, when I remove the `fixModel` function, the analysis does not work, but I don't know why. Do you have any idea?

2022-12-20 11:47 UTC, Kucharssim commented on R/plssem.R
> +  options[["models"]] <- lapply(options[["models"]], fixModel)
> @Kucharssim The only thing is that, when I remove the fixModel function, the analysis does not work, but I don't know why. Do you have any idea?

Ok, well if it doesn't work then perhaps I was wrong and you do need this. You can then leave it as is for now ;)

2022-12-20 20:04 UTC, Kucharssim approved these changes

2022-12-20 20:06 UTC, merged